### ISSUE TITLE
Install fails with pip 18.0

### ISSUE THREAD

**Issue by j0ma** [njoyce/flask-letsencrypt#1]
### Problem

Pinging @njoyce . Tried to install this extension for my Flask app today, but the install seems to be failing.

### Reproducible example

1. Verify pip version

```
[redacted]@[redacted]:~$ pip --version
pip 18.0 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)
```

2. Try installing

```
[redacted]@[redacted]:~$ pip install flask_letsencrypt
Collecting flask_letsencrypt
  Using cached https://files.pythonhosted.org/packages/5a/ad/b6e2c8d73f7e5598aa1c054a18221ec8c6915c46e3ecab1a158850951915/flask-letsencrypt-0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dbagohow/flask-letsencrypt/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ImportError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dbagohow/flask-letsencrypt/
```

The same problem persists if I clone the repository and run `setup.py` manually:

```
[redacted]@[redacted]:~/flask-letsencrypt$ sudo python setup.py
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from pip.req import parse_requirements
ImportError: No module named req
```

Any advice on what to do? Ideally I wouldn't like to downgrade `pip`. 

Happy to contribute & make the change to fix this if you can point me in the right direction a little :)

Thanks in advance!

**Comment by njoyce** [comment]
Looks like pip moved their python imports around ``pip>=10``. Seems like a change similar to https://github.com/RealKinetic/gae-utils/commit/db13ba6311597759e692c458f88da232f996c252 will be required to make it compatible.

Thanks for offering to make the fix, hopefully that commit can point you in the right direction. Lmk if you need any help.
